print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kdl:,'''',,,,,;coxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0koc::;clodxOOdcldxkxdlc:clldkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdolcldkKNMMMMMMXo:dKNWKKMMMMWKkdc:co0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMMMMWNXKOkkkxxdoollooooodxOKNWMMMMMMMMXOxl:OWMMXcxMMMMMMMMWNOo::o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMWN0xlccclllllloooc;;;lkKNWMMMMMMMMMMMMMMNxldkKNWWWOccKNNKdxNMMMMMMNOl,:OWMMMMMMMN0xkXMNOkxONMMMMMMMMMMMWKXMMMMMMMMMMMMMMNKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkddONMXKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMNOo;,;:lxk0XNWMMMMMMMWKkxONMMMMMMMMMMMMMMMM0dxkxoooollxXM0l'  oWMMMMMMMWO,.kMMMMMMMK,  d0;  'xNWNNWMWNWWWO;.oWWWNWMWWNWWMNd.,kWWNNWMWWNWMMMMMMMWNXXWMMMMWNXNWMMNc  'x0o.;0WNNWMMWNWMMWNWWMWNXXNWMMWNWWNNWMWNXNWMMMMMMMMM")
print("MMMMMMMMWKd,.;oONWMMMMMMMMMMMMMMMNOxxOKNMMMMMMMMMMMMMMWKkkkxk0KNWMMMWKxdxKWMMMMMM0xKc.xMMMMMMMK,  ..  ;KMWx';ONo':0O.  .lOl'lX0:'oKXo   'xk;'xWk,,kMMMMMXo,;c;:OWXd;,;,;xKl.  ,xc   ,dl'oN0:'c0No'oKx;',;';kWx,,;'cOx;,;,,oKMMMMMMM")
print("MMMMMMMXd..:OWMMMMMMMMMMMMMMMMMMMWXOkxkXWMMMMMMMMMMMMMMMWX0XWMMMMMMMMMNXXXNWMWWMMXOl,oNMMMMMMMK,      .dWWc .xN: .kX:  ;0O' '0O. ;OKO. .oXd  lWo  oMMMMM0, .;,,xXl  l0c  oO' .oKx. .dXx..dc   cd..kNx:,:;  ;Xo  ,x0l  .:'  cNMMMMMM")
print("MMMMMW0;.,OWMMMMMMMMMMMMMMMMMMMMMMWKOkOXMMMMMMMMMMMMMMMMWXOKWMMMMMMMMMWWNXNWMWWWWKolOWMMMMMMMMK,  ,Ol  .dNl  :d. .kMo  cX0, .oc. ;kXX; .dNx. ,x,  oMMMMMKo;:c. 'Ol  l0c  dX; .OMK, .xNNl...,d,...lN0;..l:  ,Ko  dMWo  .c;',dNMMMMMM")
print("MMMMWO' :KMMMMMMMMMMMMMMWNK0KWMMMMMN0xkKWMMMMMMMMMMMMMMMWKO0NWMMMMMMMMNK0KKXWMWXo,dNMMMMMMMMMMXl',kMNo'':00:.'::':0M0:.'oKx,.,:;'o0NWx,',kKl..;:,,kMMMMMKc,:c;,dNXd;,;,;xNNo':0MNd'';kWXl',kWk,'lXMKc';ol;'lXk,,kMMXd;,;,,oXMMMMMMM")
print("MMMM0' ,KMMMMMMMMMMMMMMMMWX0OkdxXWMWKO0KWMMMMMMMMMMMMMMMNX0kKWMMMMMMMMXXWWKXMMWx,lXMMMMMMMMMMMMWNWWMMWWWNWMWNNWWWWMMMWNXNMMWXNMWNWMMMMWXNWMWNXWWWWWMMMMMMMWNXNWMMMMWNXNWMMMWWWMMMWNXNWMMWWWWMWWWWMMMWNXNWWNWWWWWWMMMMWNXNWMMMMMMMMM")
print("MMMN: .dWMMMMMMMMMMMMMMMMMMMMW0o:ckNXkkKMMMMMMMMMMMMMMMMMXxk0ONMMMMMMMMMMWNNXOxdOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMk. '0MMMMMMMMMMMMMMMMMMMMMMMMXo';xkOXWMMMMMMMMMMMMMMMMWXkd0K0XWWKOxdooodxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMd  ;XMMMMMMMMMMMMMMMMMMMMMMMMMWk.,xOXMMMMMMMMMMMMMMMMMMWKX0xOxllccc::xKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMd  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMWl :KWMMMMMMMMMMMMMMMMMMMMWXXOxOXWXdoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMO. .OMMMMMMMMMMMMMMMMMMMMMMMMMMMx.'0MMMMMMMMMMMMMMMMMMMMMMMMMMMNx;lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMNl  cNMMMMMMMMMMMMMMMMMMMMMMMMMWd ;XMMMMMMMMMMMMMMMMMMMMMMMMMNk;,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMXc .xWMMMMMMMMMMMMMMMMMMMMMMMMO,'OWMMMXOOXMMMMMMMMMMMMMMMW0dccxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMXl..dNMMMMMMMMMMMMMMMMMMMMMNx;c0MMMMMWKdclxONMMMMMMWNKOxo::oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMWO;.;xXMMMMMMMMMMMMMMMMMWKkdkKXXXNMMMMW0l'..;coxk00kxxkOkdx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMWKxlloxOKNWMMMMMMMMMMWXOkxdooxxxKWNK0kxxddkkxxxkO0XNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMNKkxxk0KKKXXXXXKK000KXNXKNWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("MMMMMMMMMMMMMMMMMMMWNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print("version:1.0")
def suma(a, b):
    return a + b

def resta(a, b):
    return a - b

def multiplicacion(a, b):
    return a * b

def division(a, b):
    if b != 0:
        return a / b
    else:
        return "Error: No se puede dividir entre cero"

def calculadora():
    print("Selecciona una operación:")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicación")
    print("4. División")

    eleccion = input("Introduce el número de la operación (1/2/3/4): ")

    num1 = float(input("Introduce el primer número: "))
    num2 = float(input("Introduce el segundo número: "))

    if eleccion == '1':
        print("Resultado:", suma(num1, num2))
    elif eleccion == '2':
        print("Resultado:", resta(num1, num2))
    elif eleccion == '3':
        print("Resultado:", multiplicacion(num1, num2))
    elif eleccion == '4':
        print("Resultado:", division(num1, num2))
    else:
        print("Operación no válida")

# Ejecutar la calculadora
calculadora()
